#if !canImport(ObjectiveC)
import XCTest

extension MarkupCoreOrderedSetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MarkupCoreOrderedSetTests = [
        ("testInitializers", testInitializers),
        ("testInserting", testInserting),
        ("testRemoval", testRemoval),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MarkupCoreOrderedSetTests.__allTests__MarkupCoreOrderedSetTests),
    ]
}
#endif
